<?xml version="1.0" ?>
<robot name="r2d2" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find r2d2_description)/urdf/gazebo.xacro" />
    <xacro:include filename="$(find r2d2_description)/urdf/material.xacro" />
    <xacro:include filename="$(find r2d2_description)/urdf/macro.xacro" />

    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 0.010" rpy="0 0 0" />
    </joint>

    <link name="base_link">
        <xacro:default_inertial mass="10" />
        <visual>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_len}" />
            </geometry>
            <material name="body" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_len}" />
            </geometry>
        </collision>

        <!-- chassis base -->
        <visual>
            <origin xyz="0.25 0 -${leglen/2 + .05}" rpy="0 0 0" />
            <geometry>
                <box size="0.2 0.1 0.1" />
            </geometry>
            <material name="black" />
        </visual>

        <collision name="collision_chassis">
            <origin xyz="0.25 0 -${leglen/2 + .05}" rpy="0 0 0" />
            <geometry>
                <box size="0.2 ${baselen} 0.1" />
            </geometry>
        </collision>

        <!-- caster front -->
        <visual name="caster_front_visual">
            <origin xyz="0.28 0 -0.42" rpy=" 0 0 0" />
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="black" />
        </visual>

        <collision name="caster_front_collision">
            <origin xyz="0.28 0 -0.42" rpy=" 0 0 0" />
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>

    </link>

    <xacro:leg prefix="right" reflect="-1" />
    <xacro:leg prefix="left" reflect="1" />

</robot>